-- =====================================================
-- Question 1
-- Create DEPARTMENT Table
-- =====================================================
CREATE TABLE DEPARTMENT (DEPT_ID VARCHAR2(10) CONSTRAINT DEPT_ID_PK PRIMARY KEY , DEPT_NAME VARCHAR2(100) CONSTRAINT DEPT_NAME_UNIQUE UNIQUE CONSTRAINT DEPT_NAME_NOT_NULL NOT NULL , HOD_NAME VARCHAR2(100) , OFFICE_LOCATION VARCHAR2(100) , CONTACT_NUMBER NUMBER(10));
-- =====================================================
-- Question 2
-- Create STUDENT Table
-- =====================================================
CREATE TABLE STUDENT (STUDENT_ID VARCHAR2(10) CONSTRAINT STD_ID_PK PRIMARY KEY , STUDENT_NAME VARCHAR2(100)  , DOB DATE , GENDER CHAR(1) CONSTRAINT GENDER_CHECK CHECK (GENDER IN ('M' ,'F')) , MOBILE_NUMBER NUMBER(10) , EMAIL_ID VARCHAR2(50) CONSTRAINT EMAIL_ID_UNIQUE UNIQUE , CGPA NUMBER(4,2) CONSTRAINT CGPA_CHECK CHECK(CGPA BETWEEN 0 AND 10) , DEPT_ID VARCHAR2(10) CONSTRAINT DEPT_ID_FK REFERENCES DEPARTMENT (DEPT_ID));
-- =====================================================
-- Question 3
-- Create FACULTY  Table
-- =====================================================
CREATE TABLE FACULTY (FACULTY_ID VARCHAR2(10) CONSTRAINT FTY_ID_PK PRIMARY KEY , FACULTY_NAME VARCHAR2(100) , QUALIIFICATION VARCHAR2(100) , DESIGNATION VARCHAR2(100) , JOINING_DATE DATE , SALARY NUMBER (6,2) CONSTRAINT SALARY_CHECK CHECK (SALARY > 0) , EMAIL_ID VARCHAR2(100) CONSTRAINT EMAIL_UNIQUE UNIQUE , DEPT_ID VARCHAR2(10) CONSTRAINT FTY_DEPT_ID_FK REFERENCES DEPARTMENT (DEPT_ID));
-- =====================================================
-- Question 4
-- Create COURSE  Table
-- =====================================================
CREATE TABLE COURSE (COURSE_CODE VARCHAR2(10) CONSTRAINT CODE_PK PRIMARY KEY, COURSE_NAME VARCHAR2(100) CONSTRAINT COS_NAME_NOT_NULL NOT NULL , CREDITS NUMBER (2) CONSTRAINT CREDIT_CHECK CHECK(CREDITS BETWEEN 1 AND 6) , SEMESTER NUMBER(2) CONSTRAINT SEM_CHECK CHECK(SEMESTER BETWEEN 1 AND 8) , DEPT_ID VARCHAR2(10) CONSTRAINT COS_DEPT_ID_FK REFERENCES DEPARTMENT(DEPT_ID) , FACULTY_ID VARCHAR2(10) CONSTRAINT COS_FTY_FK REFERENCES FACULTY (FACULTY_ID));
-- =====================================================
-- Question 5
-- Create ENROLLMENT  Table
-- =====================================================
CREATE TABLE ENROLLMENT (ENROLLMENT_ID VARCHAR2(10) CONSTRAINT ENROL_ID_PK PRIMARY KEY, STUDENT_ID VARCHAR2(10), COURSE_CODE VARCHAR2(10), ENROLLMENT_DATE DATE DEFAULT SYSDATE, ACADEMIC_YEAR VARCHAR2(10), CONSTRAINT ENROL_STD_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID), CONSTRAINT CODE_ENROL_FK FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE), CONSTRAINT STD_COS_UK UNIQUE (STUDENT_ID, COURSE_CODE));
-- =====================================================
-- Question 6
-- Create RESULT  Table
-- =====================================================
CREATE TABLE RESULT (RESULT_ID VARCHAR2(10) CONSTRAINT RST_ID_PK PRIMARY KEY, ENROLLMENT_ID VARCHAR2(10) CONSTRAINT ENROL_ID_FK REFERENCES ENROLLMENT (ENROLLMENT_ID) , INTERNAL_MARKS NUMBER (4,2) CONSTRAINT IM_CHECK CHECK (INTERNAL_MARKS BETWEEN 0 AND 50) , EXTERNAL_MARKS NUMBER(4,2) CONSTRAINT EM_CHECK CHECK(EXTERNAL_MARKS BETWEEN 0 AND 50), TOTAL_MARKS NUMBER(5,2) , GRADE CHAR (2) CONSTRAINT GRADE_CHECK CHECK(GRADE IN ('A','B','C','D','F')), RESULT_STATUS VARCHAR2(10) CONSTRAINT RST_STS_CHECK CHECK (RESULT_STATUS IN ('PASS' ,'FAIL')));
-- =====================================================
-- Question 7
-- Create EVENT  Table
-- =====================================================
CREATE TABLE EVENT (EVENT_ID VARCHAR2(10) CONSTRAINT EVENT_ID_PK PRIMARY KEY , EVENT_NAME VARCHAR2(100) , EVENT_DATE DATE , VENU VARCHAR2(100) , FACULTY_ID VARCHAR2(10) CONSTRAINT FTY_PK_FK REFERENCES FACULTY (FACULTY_ID) , MAX_PARTICIPANTS NUMBER (7,2) CONSTRAINT MAX_CHECK CHECK (MAX_PARTICIPANTS>0) , REGISTRATION_FEE NUMBER (5,2) CONSTRAINT REG_CHECK CHECK(REGISTRATION_FEE>0));
-- =====================================================
-- Question 8
-- Create EVENT_REGISTRATION  Table
-- =====================================================
CREATE TABLE EVENT_REGISTRATION (REGISTRATION_ID VARCHAR2(10) CONSTRAINT REG_ID_PK PRIMARY KEY, EVENT_ID VARCHAR2(10) CONSTRAINT EVENT_FK REFERENCES EVENT (EVENT_ID) , STUDENT_ID VARCHAR2(10) CONSTRAINT STD_FK REFERENCES STUDENT (STUDENT_ID) , REGISTRATION_DATE DATE DEFAULT SYSDATE , PARTICIPATION_STATUS VARCHAR2(100) CONSTRAINT STATUS_CHECK CHECK (PARTICIPATION_STATUS IN ('REGISTERED','ATTENDED','ABSENT')));
